# Data & Data collections 


_______________________

### Data collections

* List
* Tuple
* Set
* Dictionary
* Numpy array
___________________________________________

### Data

* Integer
* Float
* string
* boolean
* null

In [1]:
# Let's import libraries
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# if you need to try new dataset , get the names by this simple code
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [3]:
resturant=sns.load_dataset('tips')

In [4]:
resturant

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
bill_list=list(resturant['total_bill'])
bill_tuple=tuple(resturant['total_bill'])
bill_array=np.array(resturant['total_bill'])
bill_set=set(resturant['total_bill'])

In [10]:
a=[1.5,2,3,4,5]
np.array(a)

array([1.5, 2. , 3. , 4. , 5. ])

In [20]:
np.array([5,41,'a'])

array(['5', '41', 'a'], dtype='<U11')

In [11]:
type(1)

int

In [12]:
type('dataology')

str

In [13]:
type(1.5)

float

In [15]:
type(True)

bool

In [16]:
np.nan

nan

In [17]:
[1,2,3,4,5,6,7,np.nan,78,0]

[1, 2, 3, 4, 5, 6, 7, nan, 78, 0]

In [19]:
np.array([1, 2, 3, 4, 5, 6, 7, np.nan, 78, 0]
)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan, 78.,  0.])

In [22]:
np.array([1,3,6,np.nan])

array([ 1.,  3.,  6., nan])